FROM devlikeapro/waha:latest-2026.8.1@sha256:d52ad4f394d2e48eb92d58e0f04924ff6c7621a883d08ff64176479ecd77c9ca

ARG VERSION=1.0.0
ARG GIT_SHA=dev
ARG BUILD_DATE
LABEL org.opencontainers.image.version=$VERSION org.opencontainers.image.revision=$GIT_SHA org.opencontainers.image.created=$BUILD_DATE org.opencontainers.image.title="RelayNest" org.opencontainers.image.source="https://github.com/momokii/relay-nest"

COPY docker/waha-entrypoint.sh /usr/local/bin/relaynest-waha-entrypoint.sh

ENTRYPOINT ["/bin/sh", "/usr/local/bin/relaynest-waha-entrypoint.sh"]
