FROM devlikeapro/waha:latest-2026.8.2@sha256:527ff3d634925adb26d596883d7b3ca502c080f737af3c2af2be0c973c511533

ARG VERSION=1.0.0
ARG GIT_SHA=dev
ARG BUILD_DATE
LABEL org.opencontainers.image.version=$VERSION org.opencontainers.image.revision=$GIT_SHA org.opencontainers.image.created=$BUILD_DATE org.opencontainers.image.title="RelayNest" org.opencontainers.image.source="https://github.com/momokii/relay-nest"

COPY docker/waha-entrypoint.sh /usr/local/bin/relaynest-waha-entrypoint.sh

ENTRYPOINT ["/bin/sh", "/usr/local/bin/relaynest-waha-entrypoint.sh"]
